name: Tests

on: push

jobs:
  phpunit:
    name: PHP Test
    uses: XNXKTech/workflows/.github/workflows/php-test.yml@main
    with:
      versions: "[\"8.0\", \"8.1\"]"
      stability: "[\"prefer-stable\"]"